content: |-
  {{ .Header }}

  # RBAC Example

  Recreate the RBAC examples from the [Using RBAC Authorization](https://kubernetes.io/docs/reference/access-authn-authz/rbac/) on Kubernetes documentation.

  ```hcl
  {{ include "main.tf.docs" }}
  ```

  ## Running this module manually

  1. Install [Terraform](https://www.terraform.io/) and make sure it's on your `PATH`.
  1. Run `terraform init`.
  1. Run `terraform apply`.
  1. When you're done, run `terraform destroy`.

  ## Running automated tests against this module

  1. Install [Terraform](https://www.terraform.io/) and make sure it's on your `PATH`.
  1. Install [Golang](https://golang.org/) and make sure this code is checked out into your `GOPATH`.
  1. `cd test`
  1. `go test terraform_rbac_test.go -v`

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Modules }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}
