content: |-
  {{ .Header }}

  ## Usage

  TODO

  ```hcl
  # {{ include "examples/rbac/main.tf" }}
  ```

  Please see the [rbac example](examples/rbac) for more information.

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Modules }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}
