content: |-
  {{ .Header }}

  ## Usage

    Recreate the RBAC examples from the [Using RBAC Authorization](https://kubernetes.io/docs/reference/access-authn-authz/rbac/) on Kubernetes documentation.

  ```hcl
  {{ include "main.tf" }}
  ```

  Please see the [rbac example](examples/rbac) for more information.

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Modules }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}
