content: |-
  {{ .Header }}

  # Terraform Admin Example

  Create kuberenetes service account named `terraform-admin` and pass the secret auth token to the kubernetes provider.
  Service account tokens do not expire and are ideal for deployments that take exceed 15 minutes.

  ```hcl
  {{ include "main.tf" }}
  ```

  ## Running this module manually

  1. Install [Terraform](https://www.terraform.io/) and make sure it's on your `PATH`.
  1. Run `terraform init`.
  1. Run `terraform apply`.
  1. When you're done, run `terraform destroy`.

  ## Running automated tests against this module

  1. Install [Terraform](https://www.terraform.io/) and make sure it's on your `PATH`.
  1. Install [Golang](https://golang.org/) and make sure this code is checked out into your `GOPATH`.
  1. `cd test`
  1. `go test terraform_terraform_admin_test.go -v`

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Modules }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}
