content: |-
  {{ .Header }}

  # Basic Example

  Create a Kubernetes service account with AWS S3 list and Kubernetes namespace get privileges. Then grant a pod these privileges by attaching the service account.

  ```hcl
  {{ include "main.tf" }}
  ```

  ## Running this module manually

  1. Install [Terraform](https://www.terraform.io/) and make sure it's on your `PATH`.
  1. Run `terraform init`.
  1. Run `terraform apply`.
  1. When you're done, run `terraform destroy`.

  ## Running automated tests against this module

  1. Install [Terraform](https://www.terraform.io/) and make sure it's on your `PATH`.
  1. Install [Golang](https://golang.org/) and make sure this code is checked out into your `GOPATH`.
  1. `cd test`
  1. `go test terraform_aws_iam_role_attachment_test.go -v`

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Modules }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}
